#!/bin/bash -e

# Eliminar la carpeta "externos" dentro de la carpeta distribuidora
cd distribuidora
cd externos
cd pendientes
rm lista.txt
rmdir pendientes
cd ..
rm lista.txt
cd ..
rmdir externos







